project:
  type: website
  resources: [CNAME]

execute:
  freeze: auto

jupyter: gregordimicom-venv

website:
  description: "blog - grigor dimitrov"
  site-url: https://gregordimi.com
  title: "grigor dimitrov"
  navbar:
    right:
      - resume.qmd
      - about.qmd
      - icon: github
        href: https://github.com/gregordimi
      - icon: linkedin
        href: https://www.linkedin.com/in/grigordimitrov/
  page-footer:
    left: "© 2026 grigor dimitrov"
    right:
      - icon: github
        href: https://github.com/gregordimi
      - icon: linkedin
        href: https://www.linkedin.com/in/grigordimitrov/
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme.scss, theme-dark.scss]
    css: styles.css
    search: true

editor: visual

